Document: dimbacklight
Title: Debian dimbacklight Manual
Author: <insert document author here>
Abstract: This manual describes what dimbacklight is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dimbacklight/dimbacklight.sgml.gz

Format: postscript
Files: /usr/share/doc/dimbacklight/dimbacklight.ps.gz

Format: text
Files: /usr/share/doc/dimbacklight/dimbacklight.text.gz

Format: HTML
Index: /usr/share/doc/dimbacklight/html/index.html
Files: /usr/share/doc/dimbacklight/html/*.html
